@startuml
!include ./Enums/Color.puml
!include ./Enums/TileType.puml
!include ./Utils/MessageSerializer.puml
!include ./GameAssets/FigureDTO.puml
!include ./GameAssets/GameboardDTO.puml
!include ./GameAssets/Move.puml
!include ./GameAssets/TileDTO.puml
!include ./Logger/ConsoleWriter.puml
!include ./Logger/FileWriter.puml
!include ./Logger/ILogWriter.puml
!include ./Logger/LogLevel.puml
!include ./Logger/Logger.puml
!include ./Messages/Base/IGameMessage.puml
!include ./Messages/Base/ILobbyMessage.puml
!include ./Messages/Base/IMessage.puml
!include ./Messages/Base/MessageType.puml
!include ./Messages/ClientToServer/CreateGameMessage.puml
!include ./Messages/ClientToServer/JoinGameMessage.puml
!include ./Messages/ClientToServer/LeaveGameMessage.puml
!include ./Messages/ClientToServer/ListGamesMessage.puml
!include ./Messages/ClientToServer/MoveFigureMessage.puml
!include ./Messages/ClientToServer/RollDiceMessage.puml
!include ./Messages/ClientToServer/StartGameMessage.puml
!include ./Messages/Errors/UnknownMessageTypeMessage.puml
!include ./Messages/ServerToClient/DiceResultMessage.puml
!include ./Messages/ServerToClient/GameCreatedMessage.puml
!include ./Messages/ServerToClient/GameInfoMessage.puml
!include ./Messages/ServerToClient/GameJoinedMessage.puml
!include ./Messages/ServerToClient/GameLeftMessage.puml
!include ./Messages/ServerToClient/GameOverMessage.puml
!include ./Messages/ServerToClient/GameboardUpdatedMessage.puml
!include ./Messages/ServerToClient/ListGamesResponseMessage.puml
!include ./Messages/ServerToClient/NextPlayerMessage.puml
!include ./Messages/ServerToClient/WelcomeMessage.puml
!include ./obj/Debug/net9.0/MadnShared.GlobalUsings.g.puml
!include ./obj/Debug/net9.0/.NETCoreApp,Version=v9.0.AssemblyAttributes.puml
!include ./obj/Debug/net9.0/MadnShared.AssemblyInfo.puml
!include ./obj/Debug/net8.0/MadnShared.GlobalUsings.g.puml
!include ./obj/Debug/net8.0/.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include ./obj/Debug/net8.0/MadnShared.AssemblyInfo.puml
@enduml
