@startuml
class AddCpuPlayerMessage {
    + Type : string <<get>>
}
IGameMessage <|-- AddCpuPlayerMessage
AddCpuPlayerMessage --> "GameId" Guid
AddCpuPlayerMessage --> "Difficulty" Difficulty
@enduml
